[build]
  base = "."
  command = "npm run netlify-build"
  publish = "client/build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express"]

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
